.PHONY: test

CC=c99
test: src/datastructures src/datastructures src/datastructures
	$(CC) datastructures/linkedlist/linkedlisttest.c datastructures/linkedlist/linkedlist.c -o test
	./test

clean:
	rm ./test